- name: install nginx
  sudo: yes
  apt:
    pkg: nginx
    state: latest
  notify:
    - restart nginx

- name: configure nginx
  sudo: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: configure nginx proxy
  sudo: yes
  copy:
    src: proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf
  notify:
    - restart nginx

- name: create nginx sites-available
  sudo: yes
  file:
    name: /etc/nginx/sites-available
    state: directory

- name: create nginx sites-enabled
  sudo: yes
  file:
    name: /etc/nginx/sites-enabled
    state: directory

- name: create nginx config
  sudo: yes
  template:
    src: host.j2
    dest: "/etc/nginx/sites-available/{{ item.vhost }}"
  with_items: vhosts
  notify:
    - restart nginx
