- name: add nginx apt-key
  sudo: yes
  apt_key:
    data: "{{ lookup('file', 'nginx.gpg') }}"
    state: present

- name: add nginx repository
  sudo: yes
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ wheezy nginx'
    state: present
