- name: add user
  sudo: yes
  user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    update_password: always
    groups: "{{ item.groups }}"
    state: present
  with_items: users

- name: add vhosts dir for user
  sudo: yes
  sudo_user: "{{ item.user }}"
  file:
    path: "/home/{{ item.user }}/vhosts"
    state: directory
  with_items: users
