- name: add postgresql apt-key
  apt_key: id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: yes

- name: add postgresql repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main' state=present
  sudo: yes

- name: add python-psycopg2 package
  apt: name=python-psycopg2 state=latest
  sudo: yes
