- name: add PostgreSQL user meka
  postgresql_user: name=meka password={{ meka_postgresql_password }}
  sudo: yes
  sudo_user: postgres

- name: add PostgreSQL DB meka_mezzanine
  postgresql_db: name=meka_mezzanine owner=meka encoding=UTF-8 template=template0
  sudo: yes
  sudo_user: postgres
